<a href="https://colab.research.google.com/github/ioadeer/bi-bycing-ba-2021/blob/main/test_godoy_cruz_tpot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Code to read csv file into Colaboratory:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth

from oauth2client.client import GoogleCredentials
# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [4]:
!pip install tpot

     |████████████████████████████████| 92kB 2.7MB/s 
     |████████████████████████████████| 163kB 18.3MB/s 
     |████████████████████████████████| 166.7MB 84kB/s 
  Created wheel for stopit: filename=stopit-1.1.2-cp37-none-any.whl size=11954 sha256=dbef93b8661dc9880dbbdab9655e97abfd1908a29b9b38d1c2191a7ac379cd29
  Stored in directory: /root/.cache/pip/wheels/3c/85/2b/2580190404636bfc63e8de3dff629c03bb795021e1983a6cc7
Successfully built stopit
  Found existing installation: xgboost 0.90
    Uninstalling xgboost-0.90:
      Successfully uninstalled xgboost-0.90


In [5]:

# Import required libraries
from tpot import TPOTClassifier
from sklearn.model_selection import train_test_split
import pandas as pd 
import numpy as np

/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


In [8]:
'''
https://drive.google.com/file/d/1zFhldrGPDxeyvwOQX5_GDUVUGMkZXPFf/view?usp=sharing
'''

id = '1zFhldrGPDxeyvwOQX5_GDUVUGMkZXPFf'
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('estacion-godoy-cruz-count-2020-2021-07-08-2021.csv') 
demanda_est_gc_df = pd.read_csv('estacion-godoy-cruz-count-2020-2021-07-08-2021.csv')
demanda_est_gc_df = demanda_est_gc_df.drop(['Unnamed: 0'], axis=1)
demanda_est_gc_df.head()

count  anio  nmes  ndia  wdia  hora  ...   DD  FF HORA   HUM     PNM  TEMP
0      3  2020     1     1     3     2  ...  160  13    2  72.0  1011.4  22.0
1      2  2020     1     1     3     4  ...  180  11    4  87.0  1011.8  20.9
2      1  2020     1     1     3     6  ...  180  15    6  87.0  1012.1  20.5
3      2  2020     1     1     3     7  ...  160  15    7  85.0  1013.0  20.4
4      2  2020     1     1     3    11  ...  140  17   11  63.0  1014.4  24.0

[5 rows x 13 columns]

In [25]:
demanda_est_gc_df.info()
demanda_est_gc_df['DD'][demanda_est_gc_df['DD'] =='AEROPARQUE'] = 0
demanda_est_gc_df['FF'][demanda_est_gc_df['FF'] =='AERO'] = 0
demanda_est_gc_df['FF'].astype(str).astype(int)
demanda_est_gc_df['FF'] = demanda_est_gc_df['FF'].astype(str).astype(int)
demanda_est_gc_df['DD'] = demanda_est_gc_df['DD'].astype(str).astype(int)
demanda_est_gc_df.info()
#demanda_est_gc_df[demanda_est_gc_df['DD'] =='AEROPARQUE']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7529 entries, 0 to 7528
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   count      7529 non-null   int64  
 1   anio       7529 non-null   int64  
 2   nmes       7529 non-null   int64  
 3   ndia       7529 non-null   int64  
 4   wdia       7529 non-null   int64  
 5   hora       7529 non-null   int64  
 6   dia_habil  7529 non-null   int64  
 7   DD         7529 non-null   object 
 8   FF         7529 non-null   object 
 9   HORA       7529 non-null   int64  
 10  HUM        7529 non-null   float64
 11  PNM        7529 non-null   float64
 12  TEMP       7529 non-null   float64
dtypes: float64(3), int64(8), object(2)
memory usage: 764.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7529 entries, 0 to 7528
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   count      7529 non-null   int64  
 1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [20]:
demanda_est_gc_df

count  anio  nmes  ndia  wdia  hora  ...   DD  FF HORA   HUM     PNM  TEMP
0         3  2020     1     1     3     2  ...  160  13    2  72.0  1011.4  22.0
1         2  2020     1     1     3     4  ...  180  11    4  87.0  1011.8  20.9
2         1  2020     1     1     3     6  ...  180  15    6  87.0  1012.1  20.5
3         2  2020     1     1     3     7  ...  160  15    7  85.0  1013.0  20.4
4         2  2020     1     1     3    11  ...  140  17   11  63.0  1014.4  24.0
...     ...   ...   ...   ...   ...   ...  ...  ...  ..  ...   ...     ...   ...
7524      1  2021     6   153     3    11  ...  200  13   11  73.0  1015.0  14.6
7525      2  2021     6   153     3    12  ...  180  15   12  65.0  1015.3  14.7
7526      7  2021     6   153     3    13  ...  200   9   13  56.0  1015.3  15.7
7527      1  2021     6   153     3    14  ...  230  11   14  42.0  1013.7  17.5
7528     10  2021     6   153     3    15  ...  200   9   15  40.0  1014.8  17.0

[7529 rows x 13 columns]

In [26]:
pd.isnull(demanda_est_gc_df).any()

count        False
anio         False
nmes         False
ndia         False
wdia         False
hora         False
dia_habil    False
DD           False
FF           False
HORA         False
HUM          False
PNM          False
TEMP         False
dtype: bool

In [68]:
demanda_est_gc_df_2 = demanda_est_gc_df[demanda_est_gc_df['count'] != 62]
demanda_est_gc_df_2 = demanda_est_gc_df_2[demanda_est_gc_df['count'] != 58]
demanda_est_gc_df_2 = demanda_est_gc_df_2[demanda_est_gc_df['count'] != 47]
demanda_est_gc_df_2 = demanda_est_gc_df_2[demanda_est_gc_df['count'] != 46]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  after removing the cwd from sys.path.


In [69]:
demanda_est_gc_df_2

count  anio  nmes  ndia  wdia  hora  ...   DD  FF  HORA   HUM     PNM  TEMP
0         3  2020     1     1     3     2  ...  160  13     2  72.0  1011.4  22.0
1         2  2020     1     1     3     4  ...  180  11     4  87.0  1011.8  20.9
2         1  2020     1     1     3     6  ...  180  15     6  87.0  1012.1  20.5
3         2  2020     1     1     3     7  ...  160  15     7  85.0  1013.0  20.4
4         2  2020     1     1     3    11  ...  140  17    11  63.0  1014.4  24.0
...     ...   ...   ...   ...   ...   ...  ...  ...  ..   ...   ...     ...   ...
7524      1  2021     6   153     3    11  ...  200  13    11  73.0  1015.0  14.6
7525      2  2021     6   153     3    12  ...  180  15    12  65.0  1015.3  14.7
7526      7  2021     6   153     3    13  ...  200   9    13  56.0  1015.3  15.7
7527      1  2021     6   153     3    14  ...  230  11    14  42.0  1013.7  17.5
7528     10  2021     6   153     3    15  ...  200   9    15  40.0  1014.8  17.0

[7525 rows x 13 columns]

In [94]:
demanda_est_gc_df_2 = demanda_est_gc_df_2.reset_index()
demanda_est_gc_df_2

index  count  anio  nmes  ndia  wdia  ...   DD  FF  HORA   HUM     PNM  TEMP
0         0      3  2020     1     1     3  ...  160  13     2  72.0  1011.4  22.0
1         1      2  2020     1     1     3  ...  180  11     4  87.0  1011.8  20.9
2         2      1  2020     1     1     3  ...  180  15     6  87.0  1012.1  20.5
3         3      2  2020     1     1     3  ...  160  15     7  85.0  1013.0  20.4
4         4      2  2020     1     1     3  ...  140  17    11  63.0  1014.4  24.0
...     ...    ...   ...   ...   ...   ...  ...  ...  ..   ...   ...     ...   ...
7520   7524      1  2021     6   153     3  ...  200  13    11  73.0  1015.0  14.6
7521   7525      2  2021     6   153     3  ...  180  15    12  65.0  1015.3  14.7
7522   7526      7  2021     6   153     3  ...  200   9    13  56.0  1015.3  15.7
7523   7527      1  2021     6   153     3  ...  230  11    14  42.0  1013.7  17.5
7524   7528     10  2021     6   153     3  ...  200   9    15  40.0  1014.8  17.0

[7525 rows x 14 columns]

In [70]:
demanda_est_gc_df_2['count'].unique()

array([ 3,  2,  1,  5,  9, 14,  7,  4,  6,  8, 11, 10, 12, 13, 18, 15, 20,
       23, 25, 19, 29, 27, 28, 17, 22, 41, 40, 16, 21, 31, 33, 24, 34, 37,
       38, 44, 48, 26, 42, 30, 35, 36, 61, 56, 43, 49, 39, 50, 32])

62
58
47
46

In [ ]:
for v in lista:
  print(v)
  print(demanda_est_gc_df[demanda_est_gc_df['count'] == v].count())

In [80]:
demanda_class = demanda_est_gc_df_2['count'].values
demanda_class

array([ 3,  2,  1, ...,  7,  1, 10])

In [ ]:
demanda_est_gc_df_2

In [99]:
training_indices, validation_indices = training_indices, testing_indices = train_test_split(demanda_est_gc_df_2.index, stratify = demanda, train_size=0.75, test_size=0.25)
training_indices.size, validation_indices.size

(5643, 1882)

In [101]:
tpot = TPOTClassifier(verbosity=2, max_time_mins=10, max_eval_time_mins=0.04, population_size=40)
tpot.fit(demanda_est_gc_df_2_new[training_indices], demanda[training_indices])


Generation 1 - Current best internal CV score: 1.0

Generation 2 - Current best internal CV score: 1.0

Generation 3 - Current best internal CV score: 1.0

Generation 4 - Current best internal CV score: 1.0

Generation 5 - Current best internal CV score: 1.0

Generation 6 - Current best internal CV score: 1.0

Generation 7 - Current best internal CV score: 1.0

Generation 8 - Current best internal CV score: 1.0

10.05 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: BernoulliNB(input_matrix, alpha=0.01, fit_prior=True)


TPOTClassifier(config_dict=None, crossover_rate=0.1, cv=5,
               disable_update_check=False, early_stop=None, generations=100,
               log_file=None, max_eval_time_mins=0.04, max_time_mins=10,
               memory=None, mutation_rate=0.9, n_jobs=1, offspring_size=None,
               periodic_checkpoint_folder=None, population_size=40,
               random_state=None, scoring=None, subsample=1.0, template=None,
               use_dask=False, verbosity=2, warm_start=False)

In [104]:
tpot = TPOTClassifier(verbosity=2, max_time_mins=3, max_eval_time_mins=0.04, population_size=40, random_state=42)
tpot.fit(demanda_est_gc_df_2_new[training_indices], demanda[training_indices])
#print(tpot.fit(X_train, y_train))
#print(tpot.score(X_test, y_test))
#tpot.export('tpot_iris_pipeline.py')


Generation 1 - Current best internal CV score: 0.999822695035461

Generation 2 - Current best internal CV score: 0.999822695035461

Generation 3 - Current best internal CV score: 1.0

Generation 4 - Current best internal CV score: 1.0

Generation 5 - Current best internal CV score: 1.0

Generation 6 - Current best internal CV score: 1.0

Generation 7 - Current best internal CV score: 1.0

Generation 8 - Current best internal CV score: 1.0

Generation 9 - Current best internal CV score: 1.0

Generation 10 - Current best internal CV score: 1.0

10.02 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: BernoulliNB(input_matrix, alpha=0.01, fit_prior=True)


TPOTClassifier(config_dict=None, crossover_rate=0.1, cv=5,
               disable_update_check=False, early_stop=None, generations=100,
               log_file=None, max_eval_time_mins=0.04, max_time_mins=10,
               memory=None, mutation_rate=0.9, n_jobs=1, offspring_size=None,
               periodic_checkpoint_folder=None, population_size=40,
               random_state=42, scoring=None, subsample=1.0, template=None,
               use_dask=False, verbosity=2, warm_start=False)

In [105]:
tpot.score(demanda_est_gc_df_2_new[validation_indices], demanda_est_gc_df_2.loc[validation_indices, 'count'].values)


1.0

In [107]:

tpot.export('estacion_godoy_cruz_demanda.py')

In [97]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
demandaTrans = mlb.fit_transform([{str(val)} for val in demanda_est_gc_df_2['count'].values])

demandaTrans

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]])

In [89]:
demandaTrans.shape

(7525, 49)

In [98]:
demanda_est_gc_df_2_new = demanda_est_gc_df_2.drop(['count'], axis=1)

#assert (len(titanic['Cabin'].unique()) == len(mlb.classes_)), "Not Equal" #check correct encoding done
#We then add the encoded features to form the final dataset to be used with TPOT.

demanda_est_gc_df_2_new = np.hstack((demanda_est_gc_df_2_new.values,demandaTrans))
demanda_est_gc_df_2_new.shape

(7525, 62)

In [103]:
demanda_est_gc_df_2_new

array([[0.000e+00, 2.020e+03, 1.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [1.000e+00, 2.020e+03, 1.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.000e+00, 2.020e+03, 1.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [7.526e+03, 2.021e+03, 6.000e+00, ..., 1.000e+00, 0.000e+00,
        0.000e+00],
       [7.527e+03, 2.021e+03, 6.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [7.528e+03, 2.021e+03, 6.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00]])

In [108]:
from google.colab import drive
drive.mount('/drive')

Mounted at /drive


In [110]:
demanda_est_gc_df_2.to_csv('/drive/My Drive/Datasets-bicing/estacion-godoy-cruz-demanda-final.csv')